dist: xenial
language: python
python: 3.7
branches:
  only: master
cache: 
  directories:
    - $HOME/.cache/pip
    - $VIRTUAL_ENV
jobs:
  include:
    - &python-testing
      stage: test
      env: step=TEST
      before_install: pip3 install pylint pydocstyle pytest-cov coveralls
      script: py.test --cov . && coveralls
    - <<: *python-testing
      env: step=LINT
      script: pylint *.py research/ tests/*.py
    - <<: *python-testing
      env: step=DOC
      script: pydocstyle *.py research/
