dist: trusty
language: python
python: 3.6
branches:
  only: master
cache: 
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/python3.6.3/lib/python3.6/site-packages
jobs:
  include:
    - &python-testing
      stage: test
      before_install: pip3 install pylint pydocstyle pytest-cov coveralls
      script: py.test --cov . && coveralls
    - <<: *python-testing
      script: pylint *.py tests/*.py
    - <<: *python-testing
      script: pydocstyle *.py
