dist: xenial
language: python
python: 3.7
branches:
  only: master
cache: 
  directories:
    - $HOME/.cache/pip
    - $VIRTUAL_ENV
jobs:
  include:
    - stage: test
      env: step=TEST
      before_install: pip3 install pytest-cov coveralls
      script: ci/test.sh
    - env: step=LINT
      before_install: pip3 install pylint
      script: ci/lint.sh
    - env: step=DOCSTYLE
      before_install: pip3 install pydocstyle
      script: ci/docstyle.sh
